"""create agent with relationship to tools and knowledge_bases

Revision ID: 925731b1552b
Revises: c3d61cd68afb
Create Date: 2025-05-02 10:46:55.760449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '925731b1552b'
down_revision: Union[str, None] = 'c3d61cd68afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(length=200), nullable=True),
                    sa.Column('llm_provider_id', sa.UUID(), nullable=False),
                    sa.Column('system_prompt', sa.Text(), nullable=False),
                    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.Column('is_active', sa.Integer(), nullable=False),
                    sa.Column('created_by', sa.UUID(), nullable=True),
                    sa.Column('updated_by', sa.UUID(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=True),
                    sa.ForeignKeyConstraint(['llm_provider_id'], ['llm_providers.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('agent_knowledge_bases',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('agent_id', sa.UUID(), nullable=False),
                    sa.Column('knowledge_base_id', sa.UUID(), nullable=False),
                    sa.Column('created_by', sa.UUID(), nullable=True),
                    sa.Column('updated_by', sa.UUID(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=True),
                    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
                    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('agent_tools',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('agent_id', sa.UUID(), nullable=False),
                    sa.Column('tool_id', sa.UUID(), nullable=False),
                    sa.Column('created_by', sa.UUID(), nullable=True),
                    sa.Column('updated_by', sa.UUID(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=True),
                    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
                    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_tools')
    op.drop_table('agent_knowledge_bases')
    op.drop_table('agents')
    # ### end Alembic commands ###
