"""bring database to update

Revision ID: 381429816577
Revises: 
Create Date: 2025-04-05 20:58:37.091687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381429816577'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_analysis', 'transcription')
    op.add_column('conversations', sa.Column('status', sa.String(length=255), server_default='finalized', nullable=False))
    op.add_column('conversations', sa.Column('requires_supervisor', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('conversations', sa.Column('supervisor_id', sa.UUID(), nullable=True))
    op.add_column('conversations', sa.Column('in_progress_hostility_score', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'in_progress_hostility_score')
    op.drop_column('conversations', 'supervisor_id')
    op.drop_column('conversations', 'requires_supervisor')
    op.drop_column('conversations', 'status')
    op.add_column('conversation_analysis', sa.Column('transcription', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
