"""add masked api key value

Revision ID: 79c0595f247d
Revises: c1862d33bad4
Create Date: 2025-04-11 15:19:10.076048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c0595f247d'
down_revision: Union[str, None] = 'c1862d33bad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('masked_value', sa.String(length=9), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'masked_value')
    # ### end Alembic commands ###
