"""add foreign between analysts

Revision ID: c1862d33bad4
Revises: 381429816577
Create Date: 2025-04-09 10:27:17.568959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1862d33bad4'
down_revision: Union[str, None] = '381429816577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llm_analyst', 'llm_provider_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'llm_analyst', 'llm_providers', ['llm_provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'llm_analyst', type_='foreignkey')
    op.alter_column('llm_analyst', 'llm_provider_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
