"""add welcome message column in agent

Revision ID: 8961aba78fed
Revises: 925731b1552b
Create Date: 2025-05-12 11:26:14.587378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8961aba78fed'
down_revision: Union[str, None] = '925731b1552b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('welcome_message', sa.String(length=500), nullable=False, server_default='Welcome'))
    op.add_column('agents', sa.Column('possible_queries', sa.String(length=500), nullable=False, server_default='What can you do?'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'possible_queries')
    op.drop_column('agents', 'welcome_message')
    # ### end Alembic commands ###
