"""add thumbs down and up in conversation

Revision ID: 5b024671c309
Revises: b8d9e0f12345
Create Date: 2026-02-18 11:03:40.350188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b024671c309'
down_revision: Union[str, None] = 'b8d9e0f12345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('thumbs_down_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('conversations', sa.Column('thumbs_up_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'thumbs_up_count')
    op.drop_column('conversations', 'thumbs_down_count')
    # ### end Alembic commands ###
